name: Set var test

on: [push]

jobs:
  var-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check repo content
        uses: actions/checkout@v4
        with:
          token : ${{secrets.TESTING_TOKEN1}}
      - name: set-var
        run: |
          echo "MY_VAL = Hello_mars" >> $GITHUB_ENV
      - name: display-var
        run: |
          echo "$MY_VAL"
    
      - name: setup-job
        uses: actions/setup-python@v5
        with:
          python_version : 3.12
      - name: test-var
        run: python print_py.py