name: Task-from-Chat_GPT

on:
  push:
  workflow_dispatch:

jobs:
  task1:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello GitHub Actions
        run: echo "Hello GitHub Actions"

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: print python version
        run: |
         echo "python --version
         python --version"
         


