name: Task-from-Chat_GPT

on:
  push:
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - name: access repo
        uses: actions/checkout@v5
        with:
          token: ${{secrets.TESTING_TOKEN1}}
      - name: print Hello GitHub Actions
        run: echo "Hello GitHub Actions"

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: print python version
        run: |
          python --version
          echo "api_key=${{secrets.print_key}}" >> $GITHUB_ENV
    #   - name: Install dependencies
    #     run: pip install -r requirements.txt
      - name: run python
        run: |
          echo "$api_key"
          python app.py
        
         


