name: Task-from-Chat_GPT

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 30 9 * * *

jobs:
  task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: access repo
        uses: actions/checkout@v5
        with:
          token: ${{secrets.TESTING_TOKEN1}}
          persist-credentials: true
      - name: print Hello GitHub Actions
        run: echo "Hello GitHub Actions"

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: print python version
        run: |
          python --version
          echo "api_key=${{secrets.print_key}}" >> $GITHUB_ENV
          echo "url=https://api.github.com/users/octocat" >> $GITHUB_ENV
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: run python
        run: |
          echo "the api_key length is ${#api_key} chars"
          python app.py
        #   cat test_data_saved/api_octocat.json
      - name: check for new changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git diff --staged --quiet|| echo 'new_changes=true' >> $GITHUB_ENV
      - name: commit if new changes for repo
        if: env.new_changes=='true'
        run: |
          echo '$new_changes'
          git commit -m 'new changes by workflow'
          git push
        
         


