name: Udemy Task 

on: 
#   push:
  workflow_dispatch:
#   pull_request:
  schedule:
    - cron: 0 13 * * *

jobs:
  pra1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello_world
        run: |
          echo 'Hello_World!'
          echo '$RUNNER_OS'
  pra2:
    runs-on: windows-latest
    steps:
      - name: goodbye
        run: |
          echo 'Goodbye! with exit0'  
          exit 0
      - name: exit
        run: |
          echo "I have exit0"
          echo "$RUNNER_OS"
  pra3:
    runs-on: macos-latest
    steps:
      - name: event-print
        run: |
          echo "${{github.event_name}}"
          echo '$RUNNER_OS'